version: '3'

services:
    koa-app:
        build: .
        command: npm run dev:docker
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        ports:
            - '3010:3010'

    database:
        image: postgres:11-alpine
        restart: always
        expose:
            - '5432'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: typescript-koa
