koa-app:
    build: .
    command: node_modules/.bin/nodemon app.js
    volumes:
        - .:/home/app/chat
        - /home/app/chat/node_modules
    environment:
        NODE_ENV: development
    ports:
        - '3000:3000'
