koa-app:
    build: .
    command: npm run dev:docker
    volumes:
        - .:/home/app/chat
        - /home/app/chat/node_modules
    environment:
        NODE_ENV: development
    ports:
        - '3010:3010'
